### ISSUE TITLE
[World] - China/Liaoning - Cloud disaster

### ISSUE THREAD

**Issue by KeplrOnForums** [EarthPol/EPMCIssues#10]
### Describe the issue

Words can't describe how I feel like when I decide to open up dynmap on every single towny server and see this

According to 0x its clouds translated into snow

### Coordinates

China/Manchuria, Liaoning Province

### Screenshots

![image](https://user-images.githubusercontent.com/107298824/173179684-cb968906-57f9-46d5-b5f4-d559433afa21.png)

**Comment by 0xBitMC** [comment]
Issue has been resolved by removing the snow layer that is placing snow in the wrong areas for no reason.
