### ISSUE TITLE
[World] - Kazakhstan Forest lines

### ISSUE THREAD

**Issue by KeplrOnForums** [EarthPol/EPMCIssues#11]
### Describe the issue

Probably the weirdest thing on this list. Kazakhstan looks like it had a true fight with the Uzbek tiger

### Coordinates

Central Asia/Kazakhstan

### Screenshots

![image](https://user-images.githubusercontent.com/107298824/173179756-8f55141d-92fa-4d5d-864a-3fec2737564d.png)

**Comment by 0xBitMC** [comment]
Done to the best of my ability ![image](https://user-images.githubusercontent.com/101461932/174631945-08909f5d-1e79-4bf5-a4b3-4634fbc82c2b.png)
