### ISSUE TITLE
[World] India - Bad terrain generation

### ISSUE THREAD

**Issue by KeplrOnForums** [EarthPol/EPMCIssues#12]
### Describe the issue

dont ignore this, i've did literal research and I can 100% confirm that india is not just 90% savaana desert and 10% good terrain

The only desert in india is in the northwest, the south is pretty much the same as southeast asia (savaana jungle)

I'd say it should be more Jungle-Savaana, the only desert should be the Thar Desert (circled in 1st image) 

Otherwise, the south should mostly be jungle around the coasts as well as some areas should be similar to the northern blessed terrain (i'll circle all these areas in a second image), the interior is savaanah-jungle but some hills have a few snow on them like Doddabetta (search it up for location). Also the two peninsulas of Gujurat (again, circled in a third image) should be more savaana than desert except for the northern and smaller peninsula, which is a salt desert irl.

Rest I think can stay, the northern plains is quite accurate

### Coordinates

India

### Screenshots

**Img 1: Thar desert** 

![image](https://user-images.githubusercontent.com/107298824/173179939-93aa054b-0e32-41d3-859b-41940b81febc.png)

**Img 2: Southern plains addition**

![image](https://user-images.githubusercontent.com/107298824/173179969-dcda3dd0-8d1e-4ca8-8b6b-0e6ff869ce71.png)

**Img 3: Gujurat peninsulas**

![image](https://user-images.githubusercontent.com/107298824/173179984-71392877-cb7f-4dec-a80d-d789f3e17c4e.png)

**Comment by KeplrOnForums** [comment]
I've been trying to get almost every towny server I've logged on to do this if they have an active community and an owner who listens to suggestions. I hope earthpol does this

**Comment by 0xBitMC** [comment]
> I've been trying to get almost every towny server I've logged on to do this if they have an active community and an owner who listens to suggestions. I hope earthpol does this

Perhaps we should get into a Discord Call sometime and make this generation and go over it on the call.

**Comment by KeplrOnForums** [comment]
Sorry but I don't vc. Maybe we could just message it off

**Comment by 0xBitMC** [comment]
> Sorry but I don't vc. Maybe we could just message it off

Perhaps I can stream. I would like to be able to present the edits to you and get your opinion and edit as we decide.

**Comment by 0xBitMC** [comment]
This should adjust this correctly.
![N29E060_climate](https://user-images.githubusercontent.com/101461932/174471574-c72805df-d275-4f6a-8d7e-dfa9b222f1ce.png)
![N29E075_climate](https://user-images.githubusercontent.com/101461932/174471581-87e80866-c3ee-4867-a167-c3d755a78706.png)
![N29E090_climate](https://user-images.githubusercontent.com/101461932/174471597-8b13f00b-71fa-4a19-8356-38eee8add8f9.png)
![N29E105_climate](https://user-images.githubusercontent.com/101461932/174471605-5f4d1de6-4f47-4ce8-bcc2-61f6939604f4.png)

**Comment by 0xBitMC** [comment]
![india](https://user-images.githubusercontent.com/101461932/174488764-3e0b1e4e-d64f-47ae-a17d-af3ee69e4ee3.PNG)
