### ISSUE TITLE
[Suggestion] Better solutions for travelling across land.

### ISSUE THREAD

**Issue by Wabbit-01** [EarthPol/EPMCIssues#14]
### Is your suggestion related to a problem? Please describe below.

The main problem regarding travel is the time it takes and how few options there are while maintaining the same atmosphere as in vanilla that is why i make this suggestion, it is a somewhat vanilla feature but expanded and upgraded on using custom plugins.

### Describe the solution you'd like

Trains, they would be using movecraft and only be able to travel across a certain block, a block that would act as your rail any block would work it doesn't really matter. Trains would travel quickly across land using player built rails perhaps at a speed of around 40-45m/s  and would be able to transport a hefty amount of cargo these would still be set in the same period as ships since steam powered trains have existed way back in the early 1800s. Trains would be powered by coal and would have a size around 300-500 minimum blocks to 1500-2000 maximum blocks and a chest capacity of about 5-10% all of this is theoretical and trains in game could look and function quite differently although following similar principles as the ones i have set out. Trains are a good fix as they are intuitive and customizable due to the nature of movecraft, they fit in well with the atmosphere and will be a good addition to nations and towns. They would fix the entire land travel issue without needing crummy alternatives such as hyper sped up minecarts or even worse... tp spam. They would make logistics fun and challenging while still being fairly simple to understand and put in place, they'd also be good for conflicts as nations could sabotage each others tracks during a war to cut off supply lines (maybe have a rule they can only do this during war as randomly destroying a railway for no reason is pretty cringe). All in all i think trains are the best alternative to this problem, if anyone has any others I'd love to hear but for now they seem like the best way forward when compared to the alternatives, they'll be much more fun than sitting 10 hours on a horse, boating around entire continents or spamming tp.

**Comment by pmkcanadian** [comment]
We already have a plugin that I developed awhile back called SuperRails. It would boost the speed of powered rails by up to 4x their regular speed if placed on top of a redstone block. 
I’m currently working on updating it for 1.19 as trains and movecraft don’t appreciate minecraft chunk loading.
