### ISSUE TITLE
[Bug] Economy Plugin is not saving player gold.

### ISSUE THREAD

**Issue by 0xBitMC** [EarthPol/EPMCIssues#18]
### Server

EuroPol (Beta)

### Describe the bug

When the server is stopped or restarted, any gold on the player is deleted when the server comes back online.

### To Reproduce

1. Have gold in your inventory and be online.
2. Restart the server.
3. No longer have gold in your inventory.

### Expected behavior

That you actually keep the gold that is in your inventory.

### Additional context

TheNewEconomy plugin is generally a steaming pile of garbage.

**Comment by pmkcanadian** [comment]
Further addition is Issue #19, spending any gold (by means of Towny such as /t spawn) and relogging or disconnecting also does not save the gold.

**Comment by 0xBitMC** [comment]
> Further addition is Issue #19, spending any gold (by means of Towny such as /t spawn) and relogging or disconnecting also does not save the gold.

This bug #18 is related to TNE and is no longer valid.
