### ISSUE TITLE
[Bug] All gold is taken away when doing /t spawn

### ISSUE THREAD

**Issue by darthpeti** [EarthPol/EPMCIssues#19]
### Server

EuroPol (Beta)

### Describe the bug

When you go to a town's spawn via /t spawn and it has a cost, all of your gold in your inventory is taken from you.

I initially had 14G on me , went to a  town spawn which costed 10G, and then when i checked /money it told me i had 4G, but i had none in my inventory
Once i logged off and on again, it told me i had 0G

### To Reproduce

Have 11 or more gold in your inventory
Then, go to a town's spawn via /t spawn <NAME> (which is 10g in my case)

### Expected behavior

Only 10g is taken out of your inventory

### Screenshots

I don't have any, but you can test the bug yourself iguess

**Comment by 0xBitMC** [comment]
Can you please provide a timeframe this occurred?

**Comment by darthpeti** [comment]
around 1 hour and 10 mins ago, so 12:19 GMT

**Comment by pmkcanadian** [comment]
Tested the bug myself and had another player without dev permissions do it. Exact reproduction as stated, can confirm it is true.

**Comment by 0xBitMC** [comment]
As it stands right now, this issue has been resolved with some calculation corrections.
