### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by jaiveerisnice** [EarthPol/EPMCIssues#22]
### Is your suggestion related to a problem? Please describe below.

Add sugar cane and shops.

### Describe the solution you'd like

I would like you guys to add sugar cane and shops like /n spawn so I can use gold!!!

**Comment by darthpeti** [comment]
pretty sure sugar cane is a thing on the map, i've seen a few people obtain it already

**Comment by pmkcanadian** [comment]
Sugarcane is present all around the world closer to the edges of the world, just ask around for some.
Shops will be added as soon as we are finished with a better gold plugin as the old ones are very buggy.
