### ISSUE TITLE
[Bug] Lost all the gold in my inventory

### ISSUE THREAD

**Issue by hqf5** [EarthPol/EPMCIssues#25]
### Server

EuroPol (Beta)

### Describe the bug

I was just chopping moss down on an island then 3 stacks of gold just disappeared from my inventory.

### To Reproduce

Mine moss on an island.

### Expected behavior

I didn't expect to lose my gold

### Additional context

Please can I have the gold back?
ign hqf

**Comment by pmkcanadian** [comment]
Already aware of this issue, it’s due to teleporting with /t spawn.
Gold has been refunded
