### ISSUE TITLE
[Suggestion] - Ore hotspots

### ISSUE THREAD

**Issue by KeplrOnForums** [EarthPol/EPMCIssues#31]
### Is your suggestion related to a problem? Please describe below.

There is no visible place to refer the gold hotspots.

### Describe the solution you'd like

I'd like a separate channel showing ore hotspots for all the ores in the map.

### Additional context

N/A

**Comment by kz-n** [comment]
https://earth.motfe.net/ores/

**Comment by 0xBitMC** [comment]
I am going to be changing the ore hotspots to other values and not release maps.

My reasoning for this is to bring the sense of exploration and discovery. It isn't fun when you know where everything is in the world and go there and claim resources you made an attempt to extract. I think the idea of exploring areas, coming across the discovery you have found a hotspot is special in on its own.
