### ISSUE TITLE
[Suggestion] Flavors 

### ISSUE THREAD

**Issue by iwa0297** [EarthPol/EPMCIssues#34]
### Is your suggestion related to a problem? Please describe below.

Craftable Horse armor 
Enchantable horse armor
Dog armor
Enchantable dog armor

### Describe the solution you'd like

As written above

### Additional context

Please

**Comment by kz-n** [comment]
https://github.com/DoggyCraft/MyDog

**Comment by 0xBitMC** [comment]
There is Craftable Horse Armor.

No, I'm not adding enchants or dog armor???
