### ISSUE TITLE
[Request] Add the XPBottle plugin (aka /bottle get/store)

### ISSUE THREAD

**Issue by keijodputt** [EarthPol/EPMCIssues#35]
In several Minecraft Earth/SMP servers with game mechanics common to EarthPol/EuroPol, there's a plugin that lets players store their XP levels into bottles for storage and easier retrieval later on. This plugin enables an XP based sub-economy allowing the trade of bottled XP for gold.

### Implementation

Get the BottldedExp plugin https://www.spigotmc.org/resources/bottledexp.2815/

Configure accordingly

**Comment by iwa0297** [comment]
That actually was a feature in v4

**Comment by keijodputt** [comment]
Ran some tests with an enchant table and glass bottles. Right-clicking the enchant table with empty bottles actually bottles XP. Ticket closed.
@iwa0297 FYI.
