### ISSUE TITLE
[Bug] Gold dupe with chest shops

### ISSUE THREAD

**Issue by keijodputt** [EarthPol/EPMCIssues#38]
### Server

EuroPol (Beta)

### Describe the bug

Another report coming in from JRokni, where a chest shop selling 1 item for 1g and an unaccounted number of items for sale (eg, dirt) lead to players with a gold block to buy endlessly (with some middle-steps), thus giving gold to the shop owner, but keeping them their gold, and the items they bought.

### To Reproduce

- Have someone put up a sign shop with stacks of an item for sale, 1g per item.
- Put an accessible crafting table nearby and adjust the use perms if it's in claims.
- With just a gold block in your inv, proceed to buy up to 8 items.
- Once you bought 8, go to the crafting table.
- Craft the gold block to 9 ingots, then craft the ingots back to one block.
- Buy 8 items, again.
- Rinse, repeat.

### Expected behavior

When you buy with gold blocks, the blocks must count as 9 ingots, and if no ingots are present, one block must 'disarm' to provide for currency.

**Comment by 0xBitMC** [comment]
Issue was resolved through updating/patching.
