### ISSUE TITLE
[World] Central Britain - Forestry Lines.

### ISSUE THREAD

**Issue by KeplrOnForums** [EarthPol/EPMCIssues#4]
### Describe the issue

This is yet another forest line from the map at https://earthpol.com/map . 

### Coordinates

Basically Central Britain

### Screenshots

![image](https://user-images.githubusercontent.com/107298824/173179109-6436161a-85d6-4510-9654-4b34e3c781b8.png)
![image](https://user-images.githubusercontent.com/107298824/173179116-06d88b61-05f8-4d41-9aba-e7fb3f98d75f.png)

**Comment by 0xBitMC** [comment]
![image](https://user-images.githubusercontent.com/101461932/174631662-85772727-cef5-4992-8f65-7c32b552fc59.png)
Issue Resolved.
