### ISSUE TITLE
Gold Dupe Ox this is the 1 i msged you about

### ISSUE THREAD

**Issue by Haggissss** [EarthPol/EPMCIssues#41]
### Server

EuroPol (Beta)

### Describe the bug

basically how it works is if you only have 1 gold block in your inv and you were to deposit either 1,2,3,4,5,6,7 or 8 it will put the 8 into the town bank but you will keep the block if you try to deposit 8 again while still only holding that same gold block it will say "You don't have that much." this is smart correct as the game realises that it would be duping gold so it saves the data of the block however if you craft the gold to ingots then back to a block you keep the 9 in the block so you can repeat the process infinitely.

### To Reproduce

said this in above section

### Expected behavior

im not entirley sure how this could be fixed although the most likely way i would think to do it would be to make it either when you deposit using a block the game should only allow to deposit increments of 9 (a block) or you could make it so you can only deposit ingots not blocks or maybe if you were to deposit 3 for example it would take the whole block but also return 6 ingots to the player's inventory
Here are how it could be fixed i think

### Additional context

This is basically just a copy paste of what i sent Ox

**Comment by keijodputt** [comment]
Successfully reproduced as follows:

1. Get a gold block in inventory as only currency
2. Get close to a crafting table
3. Issue a `/t deposit 8` -- This will deposit 8g in the town bank, but you'll be left with a gold block in the inventory.
4. Craft the gold block to ingots, then craft the ingots back to a gold block
5. Rinse and repeat 3-4

--keijo

**Comment by 0xBitMC** [comment]
Issue was patched.
