### ISSUE TITLE
[Bug] RELOADED: Duping gold via sign shops and a partner-in-crime

### ISSUE THREAD

**Issue by keijodputt** [EarthPol/EPMCIssues#42]
### Server

EuroPol (Beta)

### Describe the bug

There was an attempt to fix the previous gold dupe bugs that led to a twist of the bug, probably a new dupe bug. When buying from a sign shop at 1g/piece the buyer's gold doesn't disappear when it's 1 ingot what they have left, so they keep buying until the shop goes out of stock.
On the seller part, the gold doesn't add up, up to 9 ingots make for 1 block, but then the block disappears, and starts from ingots again. So, when the buyers get all the items, the seller has only 1-8 ingots or 1 block.

### To Reproduce

Set up a shop with 1 item for 1g and fill it up
Have someone buy 8 items from you
Transfer the earnings to a chest
Rinse, repeat

### Expected behavior

buyer's gold should deplete
seller's gold should grow

**Comment by 0xBitMC** [comment]
Issue was patched.
