### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by GoodIHomie** [EarthPol/EPMCIssues#44]
### Is your suggestion related to a problem? Please describe below.

hope the war chest is based on the town bank

### Describe the solution you'd like

According to town bank, stipulate war chest

**Comment by 0xBitMC** [comment]
Could you please empathize what you mean by that? I'm not sure I understand "Hope the war chest is based on the town bank?". Have you read the SiegeWar Starter Guide before?
