### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by GoodIHomie** [EarthPol/EPMCIssues#45]
### Is your suggestion related to a problem? Please describe below.

Can you add Diggus Maximus 【Vein Miner】

### Describe the solution you'd like

Can you add Diggus Maximus 【Vein Miner】

**Comment by FlintSH** [comment]
Just stop being lazy and mine the vein

**Comment by pmkcanadian** [comment]
Vein Miner is a mod and the plugin version is incredibly resource intensive.
