### ISSUE TITLE
[World] Andes

### ISSUE THREAD

**Issue by FujimotoJoeRogan** [EarthPol/EPMCIssues#50]
### Describe the issue

In the andes especially in Peru the mountains near the coast are a bit too gray and a bit too extreme, in reality it should be like terra-cotta hills that gradient to actual stone, an example of where the fade should be would in image 1m this is where the mountains are most hauntingly extreme and gray and way to close to the coast, an example of how the terrocota should be like would be in image 2, the colors should be the average badlands colors of orange, red, purple, biege though a bit more biege than normal. I hope this helps.

Image 1 ![unknown-173](https://user-images.githubusercontent.com/107424054/174647370-77d7bd1e-0606-419d-9571-83f70fd1840c.jpg)

Image 2 ![unknown-29](https://user-images.githubusercontent.com/107424054/174647380-71c3fbab-139c-4776-be3c-578fe601b880.jpg)

 

### Coordinates

N/A

### Screenshots

N/A

**Comment by 0xBitMC** [comment]
This issue will not be addressed due to mesaFilter and stoneFilter's not being able to different data layers
