### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Rebelucian** [EarthPol/EPMCIssues#59]
### Is your suggestion related to a problem? Please describe below.

No, I am suggesting that the plugin where you break the bottom of the tree and the rest of it breaks as well. This would be very helpful for gathering large amounts of wood for building ships, structures, and other things.

### Describe the solution you'd like

Add the plugin to epmc.

**Comment by darthpeti** [comment]
please DO NOT add this

**Comment by darthpeti** [comment]
🤪
Well anyways just think about it , timber plugin removes the whole purpose of grinding for wood or harvesting.

**Comment by Rebelucian** [comment]
> 🤪
> Well anyways just think about it , timber plugin removes the whole purpose of grinding for wood or harvesting.

Exactly kid! There are more important things to grind!!!

**Comment by darthpeti** [comment]
stfu "rebelucian"

**Comment by Rebelucian** [comment]
> stfu "rebelucian"

Keep copin

**Comment by darthpeti** [comment]
https://c.tenor.com/np4F_PYhEwYAAAAM/cope-copeharder.gif

**Comment by kz-n** [comment]
> > stfu "rebelucian"
> 
> Keep copin

Suck my balls rebelucian

**Comment by darthpeti** [comment]
no but fr now if ppl don't grind for stuff (even if it's just wood in this case) players will quit of boredom so you either have to make the game a little harder or give them something more to do

**Comment by darthpeti** [comment]
i mean if you want players to get 64 logs in first minute of the server sure.. unless they spawn in the desert
Atleast add a requirement like having either a netherite axe or efficiency V on your axe for timber to work so new players don't get wood easily

**Comment by Rebelucian** [comment]
That’s a good idea.

**Comment by smartfrigde** [comment]
timber plugin more like lag plugin :trollface:

**Comment by 0xBitMC** [comment]
No tree plugin.

**Comment by kz-n** [comment]
1984
Isn't there a sand one that does the same already
