### ISSUE TITLE
[Suggestion] Increase dynmap zoom range

### ISSUE THREAD

**Issue by Chocolate1Donut** [EarthPol/EPMCIssues#61]
### Is your suggestion related to a problem? Please describe below.

Wahh make the dynmap zoom out more so u can see more of earth wahh especially on big map like this

### Describe the solution you'd like

dynmap > worlds.txt

worlds:
-   name: world
    title: Earth
    enabled: true
    **extrazoomout: 3**

### Additional context

hiii im pretty sure it makes u render another layer for the dnytmap so that will suck but it will be worth it because when u can see the whole map at once its reeally coopl

**Comment by 0xBitMC** [comment]
![image](https://user-images.githubusercontent.com/101461932/176813281-a0cab542-0eee-4255-99d9-598f6492ee96.png)
We already have these settings.
