### ISSUE TITLE
[Suggestion] Allow players to charge to use ports.

### ISSUE THREAD

**Issue by FlintSH** [EarthPol/EPMCIssues#74]
### Is your suggestion related to a problem? Please describe below.

No

### Describe the solution you'd like

You should allow people to add costs to their town's ports.

Player 1 wants to get to Europe and is currently in NA.

Luckily, there is many towns in Europe with ports Player 1 can travel to, Europe sets a 10g toll to use their port.

This could be easily implemented with a confirmation in chat to continue with a teleport if it has a cost and a simple tooltip context button.

This opens a huge market for players to get into and encourages those with ports to build complex infrastructure around this mechanic that works in the greater good for all players.

**Comment by darthpeti** [comment]
will be a thing

**Comment by 0xBitMC** [comment]
Greetings @FlintSH,

Currently, any money that is paid to ports actually goes to the town and its bank. No gold disappears into a void like other teleportation plugins. This has been implemented since the start of the plugin. Therefore, I'll consider this issue resolved.

Thanks bud, hit me up btw.
