### ISSUE TITLE
[Suggestion] Changes to the Towny Price List

### ISSUE THREAD

**Issue by Taveuni** [EarthPol/EPMCIssues#75]
### Is your suggestion related to a problem? Please describe below.

N/A

### Describe the solution you'd like

The /towny prices list is highly unregulated. It first starts with simple prices like towns costing 32G to make or townblocks costing 2G, but then, it suddenly shoehorns a non sequitur by adding prices like ports costing 300G, outposts costing 500G or nations costing 2000G. I don't think any of these prices are a bad thing but nations costing 2000G is a hilarious price that doesn't really have anything to do with the prior prices.

My argument stems from the fact that one of the primary and most essential/important functions of a nation is travel and teleporting. In many Towny servers, some nations simply serve as mundane /n spawns that exist for other people to teleport, and that's about it. Why would I pay 2000G when I can just pay 300G? This is a massive stretch and I personally think it could be improved. I know the intention of setting limits to nation tp is to act as an incentive, but a 1.7k gold gap between a nation and a port doesn't really motivate people to make an effort imo.

The whole point of this proposal is to make changes to the price list. So, here's my suggestions.

1. Lower the outpost prices from 500 to 300, 350 or 380. In previous versions, outposts were mostly used for siegewar, and they're most likely going to have the same function nowadays. Paying 500 gold ingots just to disband your outpost a few days later feels like paying for an useless service, especially when players could just make a town near the town they're attacking (and join their own nation), /t toggle open, and use it as a free teleportation system for other members of the nation.

2. Lower the nation prices from 2000 to 1000 - 1500. Too much of a stretch but I've mentioned my reasoning above.

This is my whole suggestion. I don't have anything else to say.

**Comment by 0xBitMC** [comment]
Thank you, @Taveuni, for this suggestion. I have been putting some thought behind it and I think it is time to adjust the prices since the economy is reaching a stability point. I'll get back to this.

**Comment by 0xBitMC** [comment]
I have changed the prices of Towny.
