### ISSUE TITLE
[Suggestion] Add Custom Recipe for Prismarine.

### ISSUE THREAD

**Issue by Rebelucian** [EarthPol/EPMCIssues#76]
### Is your suggestion related to a problem? Please describe below.

Prismarine is unobtainable.

### Describe the solution you'd like

A custom recipe for prismarine. 

### Additional context

[](url
![PrismarineNOW](https://user-images.githubusercontent.com/84466354/180856068-5567f4e3-1119-4115-aa6d-3cba942bc451.png)
)

**Comment by Rebelucian** [comment]
-I forgot that you shou;d make it be prismarine shards so you can craft all of the prismarine blocks/sea lanterns. My bad.

**Comment by 0xBitMC** [comment]
I have completed the addition of the custom prismarine recipes.
![Prismarine Shards](https://user-images.githubusercontent.com/101461932/183163840-bb1e1c0e-a076-414f-9425-b800e2df4f97.png)
![Prismarine Crystals](https://user-images.githubusercontent.com/101461932/183163822-04e3433b-9364-46f8-a549-8bd26cfd619b.png)
