### ISSUE TITLE
sand is taking over the ocean and trapping cities

### ISSUE THREAD

**Issue by Lucas264x** [EarthPol/EPMCIssues#77]
### Describe the issue

this South American body of water is nothing but sand, when it should be ocean.

### Coordinates

-29000, 64, 18000

### Screenshots

![image](https://user-images.githubusercontent.com/65862379/181067358-dd88f6ff-4e11-4d78-adb2-352ea371e19d.png)

**Comment by darthpeti** [comment]
it's been fixed btw, dynmap is updating rn

**Comment by Lucas264x** [comment]
thx 0xbit
