### ISSUE TITLE
[Suggestion] Comayor having insufficient permissions 

### ISSUE THREAD

**Issue by catgirljodie** [EarthPol/EPMCIssues#78]
### Is your suggestion related to a problem? Please describe below.

N/A

### Describe the solution you'd like

Co-mayor having more permissions, the rank permissions don't stand for what the rank states, you cannot do much of anything in relation to the actual mayor. This lack of permission makes it difficult and challenging to achieve much in town unless you have an active mayor. Some permissions I think co-mayor should have would be the ability to un-claim chunks and being able to add someone as trusted to the town as these permissions would be found useful in a town day to day.

**Comment by 0xBitMC** [comment]
This issue was resolved with @darthpeti's updates on August 2nd.
