### ISSUE TITLE
[World] Western Africa - Forestry Lines

### ISSUE THREAD

**Issue by KeplrOnForums** [EarthPol/EPMCIssues#8]
### Describe the issue

Here's another forest line. However, you got this weird sort of "fingerprint" effect with this one, if you zoom in. These are scattered all over Africa for some reason.

### Coordinates

Western Africa

### Screenshots

Zoomed in: 
![image](https://user-images.githubusercontent.com/107298824/173179480-f71970ea-79f1-4923-8b86-6a107f4eaee4.png)
Zoomed out: 
![image](https://user-images.githubusercontent.com/107298824/173179489-acee5546-4a76-46db-86c8-5d00ff60a420.png)

**Comment by 0xBitMC** [comment]
![image](https://user-images.githubusercontent.com/101461932/174633581-7e212d27-0221-441d-a1c5-a8b26ccf9a86.png)
Issue Resolved.
