### ISSUE TITLE
make a epol support discord 

### ISSUE THREAD

**Issue by MrBlazey** [EarthPol/EPMCIssues#82]
### Is your suggestion related to a problem? Please describe below.

just a suggestion

### Describe the solution you'd like

make a fucking support epol discord for bugs, reports, appels extra ik u like github and website form type report system but tbh this is a minecraft roleplay server no one wants to use github to report shit and github isnt private as well so if your reporting a game breaking bug people can just look on github and see it and abuse it before its patched then leading people to spam staff dms which at that point is using discord anyway idk just a thought :/

**Comment by BlitzWolf007** [comment]
^

**Comment by 0xBitMC** [comment]
This has been completed. It was something we were thinking about for awhile.
